Die
int Die.faceValue
Referenced by Die, roll, setFaceValue, getFaceValue, toString.
Die.Die()
References faceValue.
int Die.roll()
References faceValue.
Referenced by Opponent.goForStraight, Opponent.goForPairs, Play.firstRoll, Play.secondThirdRolls.
void Die.setFaceValue(int value)
References faceValue.
int Die.getFaceValue()
References faceValue.
Referenced by Opponent.hasMulti, Opponent.checkStraight, Opponent.findOne, Play.main, Play.secondThirdRolls.
String Die.toString()
References faceValue.