Opponent
int Opponent.oppLogic()
References hasMulti, checkStraight, goForStraight, findOne, goForPairs.
Referenced by Play.main.
int Opponent.hasMulti()
References Player.d1, Die.getFaceValue, Player.d2, Player.d3, Player.d4, Player.d5.
Referenced by oppLogic.
int Opponent.checkStraight()
References Player.d1, Die.getFaceValue, Player.d2, Player.d3, Player.d4, Player.d5.
Referenced by oppLogic.
int Opponent.findOne()
References Player.d1, Die.getFaceValue, Player.d2, Player.d3, Player.d4, Player.d5.
Referenced by oppLogic.
void Opponent.goForStraight(int One)
References Player.d1, Die.roll, Player.d2, Player.d3, Player.d4, Player.d5.
Referenced by oppLogic.
void Opponent.goForPairs(int value)
References Player.d5, Die.roll, Player.d4, Player.d3, Player.d2, Player.d1.
Referenced by oppLogic.
Die Player.d1
Referenced by hasMulti, checkStraight, findOne, goForStraight, goForPairs, Play.firstRoll, Play.secondThirdRolls.
Die Player.d2
Referenced by hasMulti, checkStraight, findOne, goForStraight, goForPairs, Play.main, Play.firstRoll, Play.secondThirdRolls.
Die Player.d3
Referenced by hasMulti, checkStraight, findOne, goForStraight, goForPairs, Play.main, Play.firstRoll, Play.secondThirdRolls.
Die Player.d4
Referenced by hasMulti, checkStraight, findOne, goForStraight, goForPairs, Play.main, Play.firstRoll, Play.secondThirdRolls.
Die Player.d5
Referenced by hasMulti, checkStraight, findOne, goForStraight, goForPairs, Play.main, Play.firstRoll, Play.secondThirdRolls.
String Player.playerName