Play
Scanner Play.keyboard
Referenced by NumberOfOpponents, secondThirdRolls.
static void Play.main(String[] args)
References NumberOfOpponents, firstRoll, secondThirdRolls, Opponent.oppLogic, Player.d2, Die.getFaceValue, Player.d3, Player.d4, Player.d5.
static int Play.NumberOfOpponents()
References keyboard.
Referenced by main.
static void Play.firstRoll(int nOpps, Player player1, Player opponent[])
References Player.d1, Die.roll, Player.d2, Player.d3, Player.d4, Player.d5.
Referenced by main.
static void Play.secondThirdRolls(int nOpps, Player player1, Player opponent[])
References keyboard, Player.d1, Die.roll, Player.d2, Player.d3, Player.d4, Player.d5, Die.getFaceValue.
Referenced by main.